/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Precision M6700
 */
public class frmTipoContatoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmTipoContatoVIEW
     */
    public frmTipoContatoVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbFamilia = new javax.swing.JCheckBox();
        cbAmizade = new javax.swing.JCheckBox();
        cbTrabalho = new javax.swing.JCheckBox();
        cbEmergencia = new javax.swing.JCheckBox();
        btnConfirmarTipoContato = new javax.swing.JButton();
        btnCancelarTipoContato = new javax.swing.JButton();
        cbSaude = new javax.swing.JCheckBox();
        cbOutros = new javax.swing.JCheckBox();

        jCheckBox6.setText("jCheckBox6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escolha o tipo de contato desejado");

        cbFamilia.setText("Familiar");
        cbFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFamiliaActionPerformed(evt);
            }
        });

        cbAmizade.setText("Amiizade");
        cbAmizade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAmizadeActionPerformed(evt);
            }
        });

        cbTrabalho.setText("Trabalho");
        cbTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrabalhoActionPerformed(evt);
            }
        });

        cbEmergencia.setText("Emergencia");
        cbEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmergenciaActionPerformed(evt);
            }
        });

        btnConfirmarTipoContato.setText("Confirmar");
        btnConfirmarTipoContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarTipoContatoActionPerformed(evt);
            }
        });

        btnCancelarTipoContato.setText("Cancelar");
        btnCancelarTipoContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTipoContatoActionPerformed(evt);
            }
        });

        cbSaude.setText("Saude");
        cbSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSaudeActionPerformed(evt);
            }
        });

        cbOutros.setText("Outros");
        cbOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOutrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(btnConfirmarTipoContato)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelarTipoContato)
                            .addGap(35, 35, 35))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cbFamilia)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cbEmergencia)
                                    .addGap(1, 1, 1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbAmizade)
                                .addComponent(cbSaude))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbTrabalho)
                                .addComponent(cbOutros)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFamilia)
                    .addComponent(cbAmizade)
                    .addComponent(cbTrabalho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSaude)
                    .addComponent(cbOutros)
                    .addComponent(cbEmergencia))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarTipoContato)
                    .addComponent(btnCancelarTipoContato))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrabalhoActionPerformed

        if (cbTrabalho.isSelected()) {

            //bloqueando as checkbox
            cbFamilia.setEnabled(false);
            cbSaude.setEnabled(false);
        } else {

            cbFamilia.setEnabled(true);
            cbSaude.setEnabled(true);
        }
    }//GEN-LAST:event_cbTrabalhoActionPerformed

    private void btnConfirmarTipoContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTipoContatoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnConfirmarTipoContatoActionPerformed

    private void cbOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOutrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOutrosActionPerformed

    private void btnCancelarTipoContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTipoContatoActionPerformed

        //BOTAO DE CANCELAR
        cancelaNovoContato();

    }//GEN-LAST:event_btnCancelarTipoContatoActionPerformed

    private void cbAmizadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAmizadeActionPerformed

        if (cbAmizade.isSelected()) {

            //bloqueando as checkbox
            cbFamilia.setEnabled(false);
            cbSaude.setEnabled(false);

        } else {
            cbFamilia.setEnabled(true);
            cbSaude.setEnabled(true);
        }
    }//GEN-LAST:event_cbAmizadeActionPerformed

    private void cbFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFamiliaActionPerformed

        // Nao permite a seleção de todas as caixas
        if (cbFamilia.isSelected()) {

            //bloqueando as checkbox
            cbTrabalho.setEnabled(false);
            cbAmizade.setEnabled(false);
            cbSaude.setEnabled(false);

            // retornaria a tela de cadastro desse tipo de contato
        } else {

            cbTrabalho.setEnabled(true);
            cbAmizade.setEnabled(true);
            cbSaude.setEnabled(true);

        }
    }//GEN-LAST:event_cbFamiliaActionPerformed

    private void cbEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmergenciaActionPerformed
       
        if (cbEmergencia.isSelected()) {

            //bloqueando as checkbox
            cbOutros.setEnabled(false);
            cbTrabalho.setEnabled(false);
            
        } else {

            cbOutros.setEnabled(true);
            cbTrabalho.setEnabled(true);
        }
    }//GEN-LAST:event_cbEmergenciaActionPerformed

    private void cbSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSaudeActionPerformed
        
        if (cbSaude.isSelected()) {

            //bloqueando as checkbox
            cbFamilia.setEnabled(false);
            cbAmizade.setEnabled(false);
            cbTrabalho.setEnabled(false);
        } else {

            cbFamilia.setEnabled(true);
            cbAmizade.setEnabled(true);
            cbTrabalho.setEnabled(true);
        }
    }//GEN-LAST:event_cbSaudeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipoContatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipoContatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipoContatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipoContatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipoContatoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTipoContato;
    private javax.swing.JButton btnConfirmarTipoContato;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAmizade;
    private javax.swing.JCheckBox cbEmergencia;
    private javax.swing.JCheckBox cbFamilia;
    private javax.swing.JCheckBox cbOutros;
    private javax.swing.JCheckBox cbSaude;
    private javax.swing.JCheckBox cbTrabalho;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void cancelaNovoContato() {

        // MÉTDO QUE RETORNA A TELA PRINCIPAL APOS CLICLAR EM CANCELAR
        frmPrincipal objTelaPrincipalVIEW = new frmPrincipal();

        objTelaPrincipalVIEW.setVisible(true);
        dispose();
    }

}
